<?php

use Illuminate\Database\Seeder;
use \Illuminate\Support\Str;
use  \Carbon\Carbon;
class ProductSeeder extends Seeder
{

    public function run()
    {
        DB::table('products')->insert([
            [
                "title" =>$title = "New Demo Product",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/1.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Transparent Waterproof Mobile Bag for Rainy Day",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/2.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],
            [
                "title" =>$title = "GIGASONIC 19\" HD LED Monitor desktop pc monitor",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/3.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Samsung S19D300NY 18.5 Inch Business LED",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/4.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Samsung S19D300NY ",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/5.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],
            [
                "title" =>$title = "18.5 Inch Business LED",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/6.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],
            [
                "title" =>$title = "Lorem ipsum, or lipsum ",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/7.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "HP V193 LED Wide Monitor",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/8.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Demo Product Title",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/9.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Demo Product Title 2",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/10.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Jack & Jones",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/11.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Jack",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/12.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "New Formal T-shirts",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/13.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "New Casual T-shirts",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/14.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "New T-shirts",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/15.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "T-shirts",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/16.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "New Formal Shirts",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/17.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "New Casual shirts",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/18.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "New shirts",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/19.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "New Samsung Phone",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/20.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Noakia Phoen 121",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/21.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Nokia Phone model A2",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/21.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Redmi X12",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/23.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Redmi A2",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/3.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Redmi Xz",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/25.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "New Lg Full LED Monitor",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/6.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],

            [
                "title" =>$title = "Samsung Full HDD 21 monitor",
                "short_description" => $shortDescription ='100% original, we has dropshipping service , any question please fell free contact with us !',
                "slug" => Str::slug($title),
                "sku" => Str::random(8),
                "description" =>'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.' ,
                "old_price" => $price = random_int(400,500),
                "new_price" => $price + 100,
                "is_published" => 1,
                "is_new" => rand(0,1),
                "is_feature" => rand(0,1),
                "allow_review" => rand(0,1),
                "show_on_home" => rand(0,1),
                "user_id" => rand(1,7),
                "availability_id" => 1,
                "brand_id" => rand(1,10),
                "size_id" => rand(1,10),
                "color_id" => rand(0,5),
                "is_inventory" => 1,
                "inventory_qty" => 10,
                "minimum_inventory_qty" => 10,
                "notify_low_inventory" => 0,
                "warehouse_id" => rand(1,5),
                "show_availability" => 1,
                "minimum_cart_qty" => 0,
                "featured_image" => '/user/assets/images/products/27.jpg',
                "allow_seo" => 1,
                "meta_keywords" => $title,
                "meta_description" => $shortDescription,
                "available_start_date" => \Carbon\Carbon::now()->toDateTimeLocalString(),
                "available_end_date" =>Carbon::now()->addDays(29),
                "created_at" => Carbon::now()->toDateTimeLocalString(),
            ],
        ]);
    }
}
